version: '3.8'
services:
  fc2arquiteturahexagonal:
    build: .
    volumes:
      - .:/go/src
      - ./thunder-tests:/var/www/.vscode-server/data/User/globalStorage/rangav.vscode-thunder-client     
    stdin_open: true
    tty: true
